services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: ski_station
    restart: always
    depends_on:
      - db
    ports:
      - "8089:8089" 
    networks:
      - app_net

  db:
    image: mysql:5.7
    container_name: mysql_app
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - /home/vagrant/devops/mysql_app_data:/var/lib/mysql 
    networks:
      - app_net

volumes:
  mysql_app_data:

networks:
  app_net:
    driver: bridge
